### PR TITLE
Update v2.4.0.md

### PR DESCRIPTION
**Pull request by NkxxkN**
Core user input sanitization.
Sanitize an object given in input and return it.

There is no error specific to sanitization.

### CODE REVIEW

**Comment by rishabhpoddar** [comment]
Cool! One question:
- What if a key is a password, token or email type? Then we need to treat it specially right? How will the API know if that's the type of the field?

**Comment by NkxxkN** [comment]
The request object would look like:
```
{
  email: "a@gmail.com",
  password: "password",
  company: "companyName"
}
```

That would be done by the core, checking if key === "email" or key === "password", then return the fields as is.
This is invisible to the core driver interface though.

**Comment by rishabhpoddar** [comment]
I see. If you could explicitly specify special field names in the interface abs their behaviour as a comment, that would be good.

**Comment by rishabhpoddar** [comment]
And would this API throw an error for certain special field names like:
- "email" - if the syntax is incorrect
- "password" - if it's empty
- "hash32" - if it's not a 32 char hash
etc..

Because if the error is thrown, you need to specify that in the interface as well

**Comment by NkxxkN** [comment]
> And would this API throw an error for certain special field names like:

Oh ok so `sanitize` API would also be responsible for validating email/password? I thought we decided it would be done in the SDK? 

I don't understand the need for "hash32", all fields are strings provided by user input, the keys correspond to the form fields. I can't think of a scenario where a form (signup or anything else) would be asking for a hash32 user input. Let me know if that makes sense.

> I see. If you could explicitly specify special field names in the interface abs their behaviour as a comment, that would be good.

Will do after we resolved the first item from above :) 

Makes sense to mention that passwords are not sanitized, since we only store a hash version of the passwords, never render them on UI, and never use plain text passwords except when converting them to hash.

I suppose that this method could also make sure that emails have a valid format, in that case I'll add a comment about that too.

For password length, I'm not sure this is the role of this method since it's already the role of validators?

**Pull request closed without merging**
