### PR TITLE
Passwordless

### PR DESCRIPTION
**Pull request by porcellus**
Updated with resend functionality in mind

### CODE REVIEW

**Comment by rishabhpoddar** [comment]
# Feedback
- [ ] For `/recipe/signinup/code/consume POST`, we were returning the `codeId` so that users can find any custom form fields which the user entered during first code generation. The problem is that now if a user resends codes and then uses a new code, the code ID for that will be different. This means that the matching will not be possible now. So instead, we should return a the `device_id_hash` instead (we can call it `loginAttemptId` in the response)?
- [ ] In `/recipe/signinup/code POST`, if we are passing a deviceId in the input (which means that the user clicked on resending the code / link), why do we also need to pass a phoneNumber / email? If we are going to make this change, then the output of this API should also contain the email / phoneNumber.
- [ ] There are fea mentions of the work "token" in the descriptions. Please change those as we don't use token anywhere anymore.
- [ ] We can change `deviceIdHash` in `/recipe/signinup/codes GET` to `loginAttemptId`? More user friendly

**Comment by porcellus** [comment]
> `loginAttemptId`

Should we rename `failedAttempts` to `failedCodeInputs` then?

> why do we also need to pass a phoneNumber / email?

I also responded to the comment on the FDI, but the intention was to enable the backend to filter/limit resends based on the email/phoneNumber. They could just create a new code and stop before sending it (or we could have a separate endpoint to get this information by the id), but since the information is already available on the frontend we could just include it in the request. 
Passing it to the core here is a way of checking if that information was valid.

**Comment by rishabhpoddar** [comment]
# Feedback

- [ ] In the code generation API, we return the `deviceId` only in the user input code object. However, the frontend would always expect a deviceId to be returned (even in case of link based). Therefore, we should change the output of that APi to be (for status OK):
   ```
   {
      "status": "OK",
      "loginAttemptId": "kFmkPQEAJtACiT2w/K8fndEuNm+XozJXSZSlWEr+iGs=",
      "deviceId": "TU/52WOcktSv99zqaAZuWJG9BSoS0aRLfCbep8rFEwk=",
      "codeId": "QZ0Mx9zG9cfqNXmPI0I/67r9bpKghUBDQZeMMbayi+I=",
      "userInputCode": "456123",
      "linkCode": "b10lbT_SnDC4flA6Fn7pE5TtG5k5NfigLef4QMBeGA8",
      "timeCreated": 1637262633029
   }
   ```

> Should we rename failedAttempts to failedCodeInputs then?

I don't think that's needed since it's always agains the status of `INCORRECT_USER_INPUT_CODE_ERROR`.

> I also responded to the comment on the FDI,

I have responded with this in the FDI PR.

> Another way of doing this would be to provide a function on the SDK to get from deviceId to loginAttemptId (we'd need this anyway, I think), and they could store the email address and then do the rate-limiting based on that.

I don't like the idea of having this function. It just feels strange - not intuitive about how it works. Instead, we should think about returning the `loginAttemptId` to the frontend as well and accept that as an input to the APIs where we accept deviceId as an input as well. This way, this function will not be needed.

**Comment by rishabhpoddar** [comment]
- [ ] We should provide the `loginAttemptId` on the frontend and the backend, wherever possible.
- [ ] We should add the `loginAttemptId` to the generated magic link as a query param (and the `linkCode` will be the fragment part).

**Comment by porcellus** [comment]
> We should add the `loginAttemptId` to the generated magic link as a query param (and the linkCode will be the fragment part).

Made note of this in the node SDK recipe interface task

**Comment by rishabhpoddar** [comment]
As per our discussion on slack:
- Do we need to add codeId to any more APIs here?
- Should we provide a delete code endpoint (which will also delete the device if all codes are deleted - the output should indicate that?)

**Comment by rishabhpoddar** [comment]
Do you think that we need to return if the device was deleted in the `/recipe/signinup/code/remove POST` API in case that happens?

**Comment by porcellus** [comment]
We can do that, but I'm not sure if it's useful. If it's used for cleanup in the app DB, we could also return the id of the deleted device (and we could also add a separate status if the code was already deleted).
My thinking was, that if someone stores information about codes and devices, then it wouldn't make sense without also connecting them, meaning they can do their own cleanup (and would need to anyway, because of the core cleaning up devices and codes anyway)

**Comment by rishabhpoddar** [comment]
> We can do that, but I'm not sure if it's useful. If it's used for cleanup in the app DB, we could also return the id of the deleted device (and we could also add a separate status if the code was already deleted).

On second thought, you're right. It won't be useful to send info back anyway.. we can keep it how it is right now. Moving this to review done column.

**Review by rishabhpoddar — APPROVED** [review]

**Pull request merged**
